/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'mobile_banking' : IDL.Null,
  'esewa' : IDL.Null,
  'khalti' : IDL.Null,
});
export const Role = IDL.Variant({
  'provider' : IDL.Null,
  'customer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : Role,
  'phone' : IDL.Text,
});
export const Rating = IDL.Record({
  'provider' : IDL.Principal,
  'customer' : IDL.Principal,
  'createdAt' : IDL.Int,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Status = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'cleaning' : IDL.Null,
  'plumbing' : IDL.Null,
  'painting' : IDL.Null,
  'electrical' : IDL.Null,
  'moving' : IDL.Null,
});
export const Urgency = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const ServiceRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'serviceType' : ServiceType,
  'provider' : IDL.Opt(IDL.Principal),
  'urgency' : Urgency,
  'customer' : IDL.Principal,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptServiceRequest' : IDL.Func([IDL.Nat], [], []),
  'addRating' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPayment' : IDL.Func([IDL.Nat, PaymentMethod], [IDL.Nat], []),
  'getAllProviders' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllProvidersByPhone' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllRatings' : IDL.Func([], [IDL.Vec(Rating)], ['query']),
  'getAllServiceRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getAllServiceRequestsByPrice' : IDL.Func(
      [],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProviderServiceRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'getRequestsByCustomer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'getRequestsByProvider' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'getServiceRequestsByStatus' : IDL.Func(
      [Status],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'getServiceRequestsByUrgency' : IDL.Func(
      [Urgency],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfilesByRole' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getUserRatings' : IDL.Func([IDL.Principal], [IDL.Vec(Rating)], ['query']),
  'getUserServiceRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markPaymentPaid' : IDL.Func([IDL.Nat], [], []),
  'markRequestComplete' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitServiceRequest' : IDL.Func([ServiceRequest], [IDL.Nat], []),
  'updateRequestPrice' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'mobile_banking' : IDL.Null,
    'esewa' : IDL.Null,
    'khalti' : IDL.Null,
  });
  const Role = IDL.Variant({ 'provider' : IDL.Null, 'customer' : IDL.Null });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : Role,
    'phone' : IDL.Text,
  });
  const Rating = IDL.Record({
    'provider' : IDL.Principal,
    'customer' : IDL.Principal,
    'createdAt' : IDL.Int,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Status = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'cleaning' : IDL.Null,
    'plumbing' : IDL.Null,
    'painting' : IDL.Null,
    'electrical' : IDL.Null,
    'moving' : IDL.Null,
  });
  const Urgency = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ServiceRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'serviceType' : ServiceType,
    'provider' : IDL.Opt(IDL.Principal),
    'urgency' : Urgency,
    'customer' : IDL.Principal,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptServiceRequest' : IDL.Func([IDL.Nat], [], []),
    'addRating' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPayment' : IDL.Func([IDL.Nat, PaymentMethod], [IDL.Nat], []),
    'getAllProviders' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllProvidersByPhone' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllRatings' : IDL.Func([], [IDL.Vec(Rating)], ['query']),
    'getAllServiceRequests' : IDL.Func(
        [],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getAllServiceRequestsByPrice' : IDL.Func(
        [],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProviderServiceRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getRequestsByCustomer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getRequestsByProvider' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getServiceRequestsByStatus' : IDL.Func(
        [Status],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getServiceRequestsByUrgency' : IDL.Func(
        [Urgency],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfilesByRole' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getUserRatings' : IDL.Func([IDL.Principal], [IDL.Vec(Rating)], ['query']),
    'getUserServiceRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markPaymentPaid' : IDL.Func([IDL.Nat], [], []),
    'markRequestComplete' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitServiceRequest' : IDL.Func([ServiceRequest], [IDL.Nat], []),
    'updateRequestPrice' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };