/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type PaymentMethod = { 'mobile_banking' : null } |
  { 'esewa' : null } |
  { 'khalti' : null };
export interface Rating {
  'provider' : Principal,
  'customer' : Principal,
  'createdAt' : bigint,
  'comment' : string,
  'rating' : bigint,
}
export type Role = { 'provider' : null } |
  { 'customer' : null };
export interface ServiceRequest {
  'id' : bigint,
  'status' : Status,
  'serviceType' : ServiceType,
  'provider' : [] | [Principal],
  'urgency' : Urgency,
  'customer' : Principal,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'price' : bigint,
}
export type ServiceType = { 'cleaning' : null } |
  { 'plumbing' : null } |
  { 'painting' : null } |
  { 'electrical' : null } |
  { 'moving' : null };
export type Status = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'accepted' : null } |
  { 'inProgress' : null };
export type Urgency = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface UserProfile {
  'name' : string,
  'createdAt' : bigint,
  'role' : Role,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptServiceRequest' : ActorMethod<[bigint], undefined>,
  'addRating' : ActorMethod<[bigint, bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPayment' : ActorMethod<[bigint, PaymentMethod], bigint>,
  'getAllProviders' : ActorMethod<[], Array<UserProfile>>,
  'getAllProvidersByPhone' : ActorMethod<[], Array<UserProfile>>,
  'getAllRatings' : ActorMethod<[], Array<Rating>>,
  'getAllServiceRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getAllServiceRequestsByPrice' : ActorMethod<[], Array<ServiceRequest>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProviderServiceRequests' : ActorMethod<
    [Principal],
    Array<ServiceRequest>
  >,
  'getRequestsByCustomer' : ActorMethod<[Principal], Array<ServiceRequest>>,
  'getRequestsByProvider' : ActorMethod<[Principal], Array<ServiceRequest>>,
  'getServiceRequestsByStatus' : ActorMethod<[Status], Array<ServiceRequest>>,
  'getServiceRequestsByUrgency' : ActorMethod<[Urgency], Array<ServiceRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfilesByRole' : ActorMethod<[], Array<UserProfile>>,
  'getUserRatings' : ActorMethod<[Principal], Array<Rating>>,
  'getUserServiceRequests' : ActorMethod<[Principal], Array<ServiceRequest>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markPaymentPaid' : ActorMethod<[bigint], undefined>,
  'markRequestComplete' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitServiceRequest' : ActorMethod<[ServiceRequest], bigint>,
  'updateRequestPrice' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];